version: '3.8'

services:
  php:
    image: action-sociale-php:local
    container_name: action_sociale_php
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - action_sociale_network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: action_sociale_nginx
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - action_sociale_network
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: action_sociale_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: action_sociale
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./actionsociale.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - action_sociale_network

  composer:
    image: composer:latest
    container_name: action_sociale_composer
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - action_sociale_network

  node:
    image: node:18-alpine
    container_name: action_sociale_node
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - action_sociale_network

networks:
  action_sociale_network:
    driver: bridge

volumes:
  db_data: