services:
  - type: web
    name: entraide-bot
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install --legacy-peer-deps
    startCommand: node discord-bot.js
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: SYMFONY_API_URL
        value: http://roju9688.odns.fr
      - key: NODE_ENV
        value: production
